<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-ControleNota-fea9ef75-f3de-4233-a0c8-f710453261b9</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Views\Alunos\**" />
		<Content Remove="Views\Alunos\**" />
		<EmbeddedResource Remove="Views\Alunos\**" />
		<None Remove="Views\Alunos\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Views\Alunos\Create.cshtml" />
		<None Include="Views\Alunos\Delete.cshtml" />
		<None Include="Views\Alunos\Details.cshtml" />
		<None Include="Views\Alunos\Edit.cshtml" />
		<Content Include="Views\Alunos\Index.cshtml" />
	</ItemGroup>

</Project>
